public enum ClientStatement {
    SENDING_METHODS,
    WAITING_SELECTED_METHOD,
    SENDING_REQUEST,
    WAITING_DNS_RESOLVER,
    WAITING_REMOTE_HOST,
    READING_PROXY_ANSWER,
    CONTINUE_STAY_CONNECT
}
