public enum ClientStatement {
    SENDING_OPTION,
    READING_SELECTED_OPTION,
    SENDING_REQUEST,
    WAITING_DNS_RESOLVER,
    WAITING_REMOTE_HOST,
    READING_PROXY_ANSWER,
    CONTINUE_STAY_CONNECT
}
